/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab29.Huaicheng.Group1.A2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

}
